name: try

on:
  workflow_dispatch:
  push:
    branches:
      - feature_*

jobs:
  try:
    runs-on: ubuntu-latest
    steps:
      -
       name: running test
       run: |
         echo "${{ secrets.DOCKERHUB_USERNAME}}"
