name: try

on:
  workflow_dispatch:
  push:
    branches:
      - feature_*

jobs:
  try:
    runs-on: ubuntu-latest
    steps:
      -
       uses: actions/checkout@v
       name: running test
       with:
         DH_USER: ${{ secrets.DOCKERHUB_USERNAME }}
       run: |
         echo "$DH_USER"
